name: nyc_building_compliance
version: 1.0.0
config-version: 2
profile: nyc_building_compliance
model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
clean-targets: ["target", "dbt_packages"]

vars:
  minimum_building_key_coverage_pct: 99.0

models:
  nyc_building_compliance:
    +persist_docs:
      relation: true
      columns: true
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts
      quality:
        +materialized: view
