-- Read-only smoke checks after bootstrap.sql and role assignment.
-- SHOW commands return only objects visible to the active role.

USE ROLE NYC_DOB_LOADER;
USE WAREHOUSE NYC_DOB_WH;
USE DATABASE NYC_DOB_ANALYTICS;
USE SCHEMA RAW;
SELECT CURRENT_ACCOUNT(), CURRENT_USER(), CURRENT_ROLE(), CURRENT_WAREHOUSE(),
       CURRENT_DATABASE(), CURRENT_SCHEMA();
SHOW TABLES IN SCHEMA NYC_DOB_ANALYTICS.RAW;

USE ROLE NYC_DOB_TRANSFORMER;
USE WAREHOUSE NYC_DOB_WH;
USE DATABASE NYC_DOB_ANALYTICS;
USE SCHEMA DEV;
SELECT CURRENT_ACCOUNT(), CURRENT_USER(), CURRENT_ROLE(), CURRENT_WAREHOUSE(),
       CURRENT_DATABASE(), CURRENT_SCHEMA();
SHOW SCHEMAS IN DATABASE NYC_DOB_ANALYTICS;
SHOW TABLES IN SCHEMA NYC_DOB_ANALYTICS.RAW;

USE ROLE NYC_DOB_READER;
USE WAREHOUSE NYC_DOB_WH;
USE DATABASE NYC_DOB_ANALYTICS;
USE SCHEMA DEV_MARTS;
SELECT CURRENT_ACCOUNT(), CURRENT_USER(), CURRENT_ROLE(), CURRENT_WAREHOUSE(),
       CURRENT_DATABASE(), CURRENT_SCHEMA();
SHOW TABLES IN SCHEMA NYC_DOB_ANALYTICS.DEV_MARTS;
